# pytest.ini
[pytest]
pythonpath = src
addopts = --maxfail=1 --tb=short -q --cov=src  --junitxml=pytest-report.xml
markers =
  unit: marque les tests unitaires
  functional: marque les tests fonctionnels
#--disable-warnings