name: autre fichier yml
run-name: Premier fichier lancé

on:
  workflow_call:

jobs:
  other-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 add .
