name: Autre_Fichier_Yml

on:
  workflow_run:
    workflows: [CI Nico]
      types: 
        - completed
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3