name: Autre_Fichier_Yml
run-name: essai

on:
    workflow_run:
      workflows:
        - CI Nico
      types:
        - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop_ubuntu' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 add .
