name: Déploiement Nico
run-name: Déploiement de ${{ github.ref_name }} 

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Liste des fichiers (debug)
        run: ls -la

      - name: Déploiement (exemple)
        run: echo "Déploiement fictif terminé avec succès ✅"