name: Workflow complet CI CD Nico
run-name : CI CD de ${{ github.ref_name }} par ${{ github.actor }}

on: 
  push:
    branches:
      - develop_ubuntu

jobs:
  code-analysis:
    name: Code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installation des dépendances
        run: |
           python -m pip install --upgrade pip
           pip install flake8 

      - run: | 
          echo "Linting" 
          echo " Recherche les erreurs de syntaxe, les imports et variables inutiles,"
          echo " les mauvaise indentations, noms malformés, erreurs logiques simples"

      - name: Run code analysis
        run: flake8 src/ tests/


  code-reformat:
    name: Code reformat
    runs-on: ubuntu-latest
    needs: code-analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installation des dépendances
        run: |
           python -m pip install --upgrade pip
           pip install black

      - run: echo "Vérification du respect des conventions de code avec Black"
      - name: Run formatter check
        run: black --check src/ tests/

  type-checking:
    name: Type check
    runs-on: ubuntu-latest
    needs: code-reformat

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installation des dépendances
        run: |
           python -m pip install --upgrade pip
           pip install black
        
      - run: echo "Vérification des types (comme si c'était une compilation)"

      - name: Run type checker
        run: mypy src/
  
    # Security-check:
    # name: Code reformat
    # runs-on: ubuntu-latest
    # needs: type-checking

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3

    #   - name: Installation des dépendances
    #     run: |
    #        python -m pip install --upgrade pip
    #        pip install black
   
      # - run: echo "Vérification de la sécurité"
      # - name: Security check
      #   run: bandit -r src/


  unit-tests:
    name: Unit Tests (CI part 1)
    runs-on: ubuntu-latest
    needs: type-checking

    steps:
      - run: echo "Tests unitaires lancés par l'évenement ${{ github.event_name }}"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

      - name: Version de python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installation des dépendances
        run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt

      - name: Run pytest
        run : pytest -m "unit" -v --disable-warnings

  functional-tests:
    name: Functional Tests (CI part 3)
    runs-on: ubuntu-latest
    needs: unit-tests  # Optionnel : exécute les tests fonctionnels après les tests unitaires

    steps:
      - run: echo "Tests fontionnels lancés si les tests unitaires ont eu lieu"

      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

      - name: Version de python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installation des dépendances
        run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt

      - name : Run functional tests
        run: |
          pytest -m "functional" -v --disable-warnings

  call-example:
    name: CI part 2 (after part 1)
    uses: ./.github/workflows/after_unit_tests.yml
    needs: unit-tests

  call-deployment:
    name: Deploy on docker (after part 3)
    uses: ./.github/workflows/cd-nico.yml
    needs: functional-tests