name: CI_Nico
run-name : Intégration de ${{ github.ref_name }} par ${{ github.actor }}

on: 
  push:
    branches:
      - develop_ubuntu

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - run: echo "Tests unitaires lancés par l'évenement ${{ github.event_name }}"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

      - name: Version de python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installation des dépendances
        run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt

      - name: Run pytest
        run : pytest -m "unit" -v --disable-warnings

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    needs: unit-tests  # Optionnel : exécute les tests fonctionnels après les tests unitaires

    steps:
      - run: echo "Tests fontionnels lancés si les tests unitaires ont eu lieu"

      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

      - name: Version de python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installation des dépendances
        run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt

      - name : Run functional tests
        run: |
          pytest -m "functional" -v --disable-warnings